spring.application.name=quanlyhaisan
spring.datasource.url=jdbc:mysql://localhost:3306/quanlyhaisan?useSSL=false
spring.datasource.username=root
spring.datasource.password=LA.luvina1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

